CREATE TABLE demo (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO demo (name) VALUES ('Alice');
INSERT INTO demo (name) VALUES ('Bob');
INSERT INTO demo (name) VALUES ('Charlie');