services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bookworm
    container_name: aas_hub
    volumes:
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 9000:9000
      - 3000:3000
  
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aashub
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "9001:80"
    depends_on:
      - mariadb

volumes:
  mysql-data: