name: Go Formatting

on:
  pull_request:
    paths:
      - 'backend/aashub/**'
  push:
    branches: [main]
    paths:
      - 'backend/aashub/**'

jobs:
  gofmt:
    name: GoFmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22.5'

      - name: Run GoFmt
        id: gofmt-run
        run: |
          gofmt -d backend/aashub/ > gofmt_output.txt
          if [ -s gofmt_output.txt ]; then
            echo "Formatting issues found:"
            cat gofmt_output.txt
            exit 1
          fi

      - name: GoFmt Output
        if: failure()
        run: echo "Check formatting issues in the logs."
