name: Code Formatting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'

      - name: Install Prettier
        run: |
          npm install --global prettier@latest
          npm install --global prettier-plugin-vue

      - name: Run Prettier
        id: prettier-run
        run: |
          echo "prettier-output<<EOF" >> $GITHUB_ENV
          prettier --list-different --config ./.prettierrc --ignore-path ./.prettierignore **/*.ts **/*.vue **/*.json **/*.js | tee -a $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "The following files are not formatted:"
          echo "${{ env.prettier-output }}"